functionsDirectory = "C:\\VitaLink Site\\netlify\\functions"
functionsDirectoryOrigin = "default"
plugins = []

[build]
publish = "C:\\VitaLink Site"
publishOrigin = "default"
functions = "C:\\VitaLink Site\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions.auto-cms-pbp-import]
schedule = "*/3 10-15 1 10 *"

[functions."*"]

[[headers]]
for = "/sitemap.xml"

[headers.values]
Content-Type = "application/xml; charset=UTF-8"

[[headers]]
for = "/robots.txt"

[headers.values]
Content-Type = "text/plain; charset=UTF-8"

[[headers]]
for = "/llms.txt"

[headers.values]
Content-Type = "text/plain; charset=UTF-8"

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/privacy"
to = "/privacy.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/terms"
to = "/terms.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/emergency.html"
to = "/emergency.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/index.html"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/agents"
to = "/agents.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/agent-access"
to = "/agent-access.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/reach"
to = "/reach.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/crm-sales"
to = "/crm-sales.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/crm-access"
to = "/crm-sales.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/platform-under-development"
to = "/platform-under-development.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/agent-promo"
to = "/agent-promo.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/agent-resources"
to = "/agent-resources.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/rsm-register"
to = "/rsm-register.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/rsm-onboard"
to = "/core-node/rsm_onboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/agent-portal-activation"
to = "/agent-portal-activation.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/activate"
to = "/activate.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/quick_start"
to = "/quick_start.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/what-is-vitalink"
to = "/what-is-vitalink.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/emergency-qr-access"
to = "/emergency-qr-access.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/medication-organization"
to = "/medication-organization.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/health-information-management"
to = "/health-information-management.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/for-insurance-agents"
to = "/for-insurance-agents.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/for-agencies"
to = "/for-agencies.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/for-organizations"
to = "/for-organizations.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/industry-partners"
to = "/industry-partners.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/for-individuals"
to = "/for-individuals.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/schedule-demo"
to = "/schedule-demo.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/referral/:token"
to = "/referral.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/marketing-crm"
to = "/marketing-crm/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/crm/vitalink-notifications"
to = "/crm/vitalink-notifications.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]